//TYPES USUARIO
export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const OBTENER_USUARIOERROR = "OBTENER_USUARIOERROR";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CERRAR_SESION = "CERRAR_SESION";
//TYPES EMAILS
export const GETEMAILS_EXITOSO = "GETEMAILS_EXITOSO";
export const GETEMAILS_ERROR = "GETEMAILS_ERROR";
export const AGREGAR_EMAIL = "AGREGAR_EMAIL";
export const AGREGAR_EMAILERROR = "AGREGAR_EMAILERROR";
export const ELIMINAR_EMAIL = "ELIMINAR_EMAIL";
//TYPES PHONE
export const GETPHONES_EXITOSO = "GETPHONES_EXITOSO";
export const GETPHONES_ERROR = "GETPHONES_ERROR";
export const AGREGAR_PHONE = "AGREGAR_PHONE";
export const AGREGAR_PHONEERROR = "AGREGAR_PHONEERROR";
export const ELIMINAR_PHONE = "ELIMINAR_PHONE";
